### ISSUE TITLE
Koap github pages deployment down

### ISSUE THREAD

**Issue by bdunlay** [JuulLabs/koap#205]
Looks like the koap page hosted on github pages is down, in case you weren't aware.

**Comment by bdunlay** [comment]
https://juullabs.github.io/koap/

**Comment by twyatt** [comment]
Oh dang. I was not aware, thanks for the heads up!

**Comment by twyatt** [comment]
Should be fixed now.
Thanks for reporting @bdunlay!

**Comment by bdunlay** [comment]
Thanks for the useful tool!
