### ISSUE TITLE
Public API Not Directly Usable From Javascript

### ISSUE THREAD

**Issue by davidtaylor-juul** [JuulLabs/koap#32]
Unable to invoke the `Message.encode` method from js, method is defined here:
https://github.com/JuulLabs/koap/blob/main/koap/src/commonMain/kotlin/Encoder.kt#L56

Example:
```js
import koapModule from '@juullabs/koap'
import kotlin from 'kotlin'
const koap = koapModule.com.juul.koap
let token = new kotlin.Long(66)
let emptyPayload = new Uint8Array()
let kMsg = new koap.Message.Tcp(
    koap.Message.Code.Method.GET,
    token,
    new kotlin.kotlin.collections.ArrayList(
        [
            new koap.Message.Option.UriPath("dev"),
            new koap.Message.Option.UriQuery("abd")
        ]
    ),
    emptyPayload
}
let outMsg = koap.encode(kMsg)
```

Results in the exception: "Unhandled Rejection (TypeError): koap.encode is not a function"

IMHO there needs to be some javascript unit tests added to exercise the API to verify it performs as expected when published as a library.

**Comment by twyatt** [comment]
@davidtaylor-juul #35 fixes this issue, right? (i.e. can this issue be closed out now?)

**Comment by davidtaylor-juul** [comment]
While #35 fixes the name mangling there are further issues preventing direct usage from Javascript. I recommend holding this ticket open until we can provide a slightly massaged API for js consumption and show a working example.

**Comment by davidtaylor-juul** [comment]
I actually do have it working now. The issue was difficulty of interop with parts of the API that require `List<T>` objects an the inability to invoke `Array.toList()`.

The solution is to use `ArrayList` instead and javascript arrays can be converted to such e.g.:
```js
let myList = new kotlin.kotlin.collections.ArrayList(['a','b','c'])
```

Have updated the above example to suit. The syntax is pretty wild but this does the trick so this issue can indeed be closed now.
